// Configuration-only regression checks; synthetic fixtures, no HTTP or queue writes.
const fs=require('fs'),cp=require('child_process'),os=require('os'),path=require('path');
const root=path.resolve(__dirname,'..'),isCon=fs.existsSync(root+'/lib/bootstrap.php');
const fixture=fs.mkdtempSync(path.join(process.env.VENDERCRM_TEST_TMP || os.tmpdir(),'vendercrm-config-'));
const php=process.env.PHP_BINARY || 'php';
function phpArray(obj){return '<?php return '+JSON.stringify(obj).replace(/^\{/,'[').replace(/\}$/,']').replace(/"([^"]+)":/g,'"$1"=>')+';';}
let count=0;
function run(name,settings,expected,fail=false){const home=fixture+'/'+name,pub=home+'/public';fs.mkdirSync(pub+'/lib',{recursive:true});fs.mkdirSync(home+'/private');if(settings.legacy)fs.writeFileSync(isCon?pub+'/config.crm.php':home+'/vendercrm-config.php',phpArray(settings.legacy));if(settings.shared)fs.writeFileSync(home+'/private/vendercrm.php',phpArray(settings.shared).replace('<?php ',"<?php if(isset($GLOBALS['fixtureLoaded'])) throw new RuntimeException('duplicate-load'); $GLOBALS['fixtureLoaded']=true; echo 'suppressed-synthetic-output'; "));fs.copyFileSync(root+'/lib/vendercrm-config.php',pub+'/lib/vendercrm-config.php');let body;if(isCon){const source=fs.readFileSync(root+'/lib/bootstrap.php','utf8');body=source.slice(source.indexOf('function cfg('),source.indexOf('/**\n * A content',source.indexOf('function cfg('))>0?source.indexOf('/**\n * A content',source.indexOf('function cfg(')):source.indexOf('/**\r\n * A content',source.indexOf('function cfg(')));fs.writeFileSync(pub+'/config.example.php',phpArray({SITE_URL:'preserved'}));body="define('ROOT_DIR',"+JSON.stringify(pub)+");"+body+"$result=['url'=>cfg('VENDERCRM_URL'),'api_key'=>cfg('VENDERCRM_API_KEY'),'site'=>cfg('SITE_URL')];";}else body="require "+JSON.stringify(root+'/lib/lead-delivery.php')+"; $result=TasacionLeadDelivery::config("+JSON.stringify(pub)+");";
const env={...process.env};for(const key of ['VENDERCRM_URL','VENDERCRM_API_KEY','VENDERCRM_CONFIG_FILE','VCRM_ENDPOINT','VCRM_SITE_KEY','TASACION_OUTBOX_DIR'])delete env[key];Object.assign(env,settings.env||{});const check=fail?(isCon?"if($result['url']!==null||$result['api_key']!==null||$result['site']!=='preserved')exit(3);":"exit(3);"):Object.entries(expected).map(([k,v])=>"if(($result["+JSON.stringify(k)+"]??null)!=="+JSON.stringify(v)+")exit(4);").join('');const script="try {"+body+check+"}catch(Throwable $e){"+(fail&&!isCon?"exit(0);":"exit(5);")+"}";const result=cp.spawnSync(php,['-r',script],{env,encoding:'utf8'});if(result.stdout!=='')throw Error(name+' leaked private config output');if(result.status!==0)throw Error(name+' failed ('+result.status+')');count++;}
const upper={VENDERCRM_URL:'https://crm.example.com',VENDERCRM_API_KEY:'synthetic-only'},old={url:'https://legacy.example.com/api/v1/leads',api_key:'legacy-synthetic',outbox_dir:'E:/synthetic-outbox'};
if(isCon){run('root-fallback',{legacy:upper},{url:upper.VENDERCRM_URL,api_key:upper.VENDERCRM_API_KEY,site:'preserved'});run('env-compatibility',{env:{VCRM_ENDPOINT:'https://legacy.example.com/api/v1/leads',VCRM_SITE_KEY:'legacy-synthetic'}},{url:'https://legacy.example.com/api/v1/leads',api_key:'legacy-synthetic'});run('shared-precedence',{shared:upper,legacy:{VENDERCRM_URL:'https://old.example.com',VENDERCRM_API_KEY:'old-synthetic'},env:{VENDERCRM_URL:'https://env.example.com',VENDERCRM_API_KEY:'env-synthetic'}},{url:upper.VENDERCRM_URL,api_key:upper.VENDERCRM_API_KEY,site:'preserved'});run('partial-shared',{shared:{VENDERCRM_URL:upper.VENDERCRM_URL}},{},true);run('route-rejected',{shared:{...upper,VENDERCRM_URL:'https://crm.example.com/api/v1/leads'}},{},true);}
else{run('legacy-fallback',{legacy:old},old);run('shared-precedence',{legacy:old,shared:{...upper,outbox_dir:'E:/ignored-synthetic-outbox'}},{url:upper.VENDERCRM_URL,api_key:upper.VENDERCRM_API_KEY,outbox_dir:old.outbox_dir});run('legacy-aliases',{legacy:{...old,...upper}},{url:upper.VENDERCRM_URL,api_key:upper.VENDERCRM_API_KEY,outbox_dir:old.outbox_dir});run('env-last',{shared:{...upper,outbox_dir:'E:/private-outbox'},env:{VENDERCRM_URL:'https://env.example.com',VENDERCRM_API_KEY:'env-synthetic',TASACION_OUTBOX_DIR:'E:/env-outbox'}},{url:'https://env.example.com',api_key:'env-synthetic',outbox_dir:'E:/env-outbox'});run('partial-shared',{shared:{VENDERCRM_URL:upper.VENDERCRM_URL}},{},true);run('route-rejected',{shared:{...upper,VENDERCRM_URL:'https://crm.example.com/api/v1/leads'}},{},true);}
console.log(count+' configuration cases PASS');
